# BASIC MATH FUNCTION
# Arithmatic operations of Numpy arrays
# > substraction(-)
# > multiplication(*)
# > Division(/)
# > matrix multiplication(@)
# > Modulo(%)
# > Transpose
# > Exponentiation(**)
# > Floor Division(//)

1. additin of numpy elements

In [1]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.sum((n1,n2))

100

In [1]:
# Addition
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
z=n1+n2
print(z)

[40 60]


In [2]:
# substraction
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
z=n1-n2
print(z)

[-20 -20]


In [3]:
# Matrix multiplication
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
z=n1@n2
print(z)

1100


2. Basic multiplication 

In [3]:
import numpy as np
n1=np.array([10,20])
n1=n1*2
n1

array([20, 40])

3.Basic Addition

In [4]:
import numpy as np
n1=np.array([10,20])
n1=n1+1
n1

array([11, 21])

4. basic substraction

In [5]:
import numpy as np
n1=np.array([10,20])
n1=n1-1
n1

array([ 9, 19])

4. basic division

In [7]:
# division
import numpy as np
n1=np.array([10,20])
n1=n1/2
n1

array([ 5., 10.])

In [6]:
import numpy as np
n1=np.array([[10,20],[60,70]])
n2=np.array([[30,40],[80,90]])
z=n1/n2
print(z)

[[0.33333333 0.5       ]
 [0.75       0.77777778]]


In [7]:
# floor division
import numpy as np
n1=np.array([[10,20],[60,70]])
n2=np.array([[30,40],[80,90]])
z=n1//n2
print(z)

[[0 0]
 [0 0]]


In [8]:
# Exponentiation
import numpy as np
n1=np.array([[10,20],[60,70]])
n2=np.array([[30,40],[80,90]])
z=n1**n2
print(z)

[[1073741824          0]
 [         0          0]]


In [9]:
# Modulo
import numpy as np
n1=np.array([[10,20],[60,70]])
n2=np.array([[30,40],[80,90]])
z=n1%n2
print(z)

[[10 20]
 [60 70]]


NUMPY MATH FUNCTION

In [11]:
# Transpose
import numpy as np
n1=np.array([[10,20],[60,70]])
print(n1.transpose)

<built-in method transpose of numpy.ndarray object at 0x0000021B92883D50>


In [14]:
# 1. mean
import numpy as np
n1=np.array([10,20])
np.mean(n1)

15.0

In [13]:
n1=np.array([10,20])
np.median(n1)

15.0

# # Sorting arrays in Numpy
# >np.sort()--(It will returns a sorting copy of an array)
# >np.arg()-- (return the Indices that would sort an array)
# >ndarray.sort()--(use array name and sort it in place)

In [27]:
# sorting in Assending order (By-default)
x=np.array([1,4,5,7,3,8,3,9])
y=np.sort(x)
print(y)

[1 3 3 4 5 7 8 9]


In [29]:
# To sorting in Desending order
x=np.array([1,4,5,7,3,8,3,9])
y=np.sort(x)[::-1]
print(y)

[9 8 7 5 4 3 3 1]


In [28]:
x=np.array([1,4,5,7,3,8,3,9])
y=np.argsort(x)
print(y)

[0 4 6 1 2 3 5 7]


# Sorting 2-D arrays in Numpy

In [25]:
# sorting column-wise
x=np.array([[12,13,18],[14,17,15],[19,25,21]])
print(x)
x.sort()
print(x)

[[12 13 18]
 [14 17 15]
 [19 25 21]]
[[12 13 18]
 [14 15 17]
 [19 21 25]]


In [21]:
# sorting row-wise(bydefoult)
x=np.array([[12,13,18],[14,17,15],[19,25,21]])
print(x)
z=np.sort(x)
print(z)

[[12 13 18]
 [14 17 15]
 [19 25 21]]
[[12 13 18]
 [14 15 17]
 [19 21 25]]


In [22]:
# sorting column-wise
x=np.array([[12,13,18],[14,17,15],[19,25,21]])
print(x)
z=np.sort(x,axis=0)
print(z)

[[12 13 18]
 [14 17 15]
 [19 25 21]]
[[12 13 15]
 [14 17 18]
 [19 25 21]]


In [23]:
# sorting column-wise
x=np.array([[12,13,18],[14,17,15],[19,25,21]])
print(x)
z=np.argsort(x,axis=0)
print(z)

[[12 13 18]
 [14 17 15]
 [19 25 21]]
[[0 0 1]
 [1 1 0]
 [2 2 2]]


In [24]:
# sorting row-wise
x=np.array([[12,13,18],[14,17,15],[19,25,21]])
print(x)
z=np.argsort(x,axis=1)
print(z)

[[12 13 18]
 [14 17 15]
 [19 25 21]]
[[0 1 2]
 [0 2 1]
 [0 2 1]]
