# Intro for Numpy :-

Libraries in python=[Packages]
Python library is a collection of functions and methods that allows you to perform many action without writing your code

#             Python Numpy  

# numpy stands for numerical python
# It is core library for numeric and scientific computing
# It consists of multi dimentional array object and a collection of routines for processing those arrays

#         creating numpy array

# single dimensional array-(one list)

#  In Numpy is an Fundamental Object
> arrays are used to store homogeneous data elements in contiguous block  memory (allocate contiguously memory )

# > all elements of an arrays are of same data type
# > Elements of an array are store in contiguous memory location
# > Arrays are static and cannot be realized once they are created
# > Arrays support element wise operation
# > NumPy array takes up less space in memory

In [2]:
import numpy as np
n1=np.array([10,20,30])
n1

array([10, 20, 30])

In [5]:
import numpy as np
n2=np.array(([12,34,56],[23,45,67]))
n2

array([[12, 34, 56],
       [23, 45, 67]])

#    Initializing numpy array

# Initializing Numpy arrays with zeros 

In [12]:
import numpy as np 
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [13]:
import numpy as np 
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Initializing Numpy arrays with same numbers :

In [14]:
import numpy as np 
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

# Initializing Numpy arrays within a range :

In [17]:
import numpy as np 
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
import numpy as np 
n1=np.arange(10,20,2)
n1

array([10, 12, 14, 16, 18])

# Initializing Numpy array with a random numbers :

In [20]:
import numpy as np 
n1=np.random.randint(1,100,8)
n1

array([ 1, 80, 23, 23, 67, 28, 14, 91])

#                    Attributes
# > shape
# > size
# > ndim
# > itemsize
# > dtype

#     checking the shape of numpy arrays

In [2]:
import numpy as np 
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [4]:
import numpy as numpy
list1=[[10,20,30],[40,50,60],[70,80,90]]
n1=np.array(list1)
n1.ndim

2

In [6]:
import numpy as np 
list1=[[10,20,30],[40,50,60],[70,80,90]]
n1=np.array(list1)
print(n1)
n1.shape

[[10 20 30]
 [40 50 60]
 [70 80 90]]


(3, 3)

In [7]:
import numpy as np 
list1=[[10,20,30],[40,50,60],[70,80,90]]
n1=np.array(list1)
print(n1)
n1.size

[[10 20 30]
 [40 50 60]
 [70 80 90]]


9

In [10]:
import numpy as np 
list1=[[10,20,30],[40,50,60],[70,80,90]]
n1=np.array(list1)
print(n1)
n1.dtype

[[10 20 30]
 [40 50 60]
 [70 80 90]]


dtype('int32')

> itemsize take bit allocation

In [11]:
import numpy as np 
list1=[[10,20,30],[40,50,60],[70,80,90]]
n1=np.array(list1)
print(n1)
n1.itemsize

[[10 20 30]
 [40 50 60]
 [70 80 90]]


4

# joining numpy arrays

1. Vertically joining array
#  > vstack ()

In [1]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.vstack((n1,n2))

array([[10, 20],
       [30, 40]])

2. Horizopntaly joining arrays
   # > hstack ()

In [2]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.hstack((n1,n2))

array([10, 20, 30, 40])

3. column hoining arrays
# > column_stack()

In [3]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.column_stack((n1,n2))

array([[10, 30],
       [20, 40]])

In [4]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.row_stack((n1,n2))

array([[10, 20],
       [30, 40]])

# indexing in numpy arrays
> used to acess the elements in arrays

In [2]:
 #    one dimension
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[0])

10


In [3]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[-2])

50


In [8]:
import numpy as np
n1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(n1)
print(n1[1,2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
60


In [10]:
import numpy as np
n1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(n1[0,:])

[10 20 30]


In [11]:
import numpy as np
n1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(n1[:,1])

[20 50 80]


# slicing in numpy arrays
# > used to acess the subset of data from numpy arrays
# > syntax : [start,stop,step]

In [1]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[1:4])

[20 30 40]


In [2]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[1:5:2])

[20 40]


In [3]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[-1:-5:-2])

[60 40]


In [4]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[::4])

[10 50]


In [5]:
# it print in reverse direction of array
import numpy as np
n1=np.array([10,20,30,40,50,60])
print(n1[::-1])

[60 50 40 30 20 10]


In [7]:
#     two dimention
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 200 300]]


In [8]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[1,])

[40 50 60]


In [9]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[:,1])

[ 20  50  80 200]


In [10]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[1:3,1:3])

[[50 60]
 [80 90]]


In [11]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[1:3,])

[[40 50 60]
 [70 80 90]]


In [13]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[:,1:3])

[[ 20  30]
 [ 50  60]
 [ 80  90]
 [200 300]]


In [14]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[1:3,1])

[50 80]


In [15]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90],[100,200,300]])
print(n1[1:3,:1])

[[40]
 [70]]
